name: expense_manager
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  get: ^4.6.6
  video_player: ^2.9.1
  uuid: ^4.4.2
  cloud_firestore: ^5.1.0
  intl: ^0.19.0
  animate_do: ^3.3.4
  pdf: ^3.11.0
  open_file: ^3.3.2
  path_provider: ^2.1.4
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsLight.ttf
        - asset: assets/fonts/PoppinsMedium.ttf
        - asset: assets/fonts/PoppinsRegular.ttf
        - asset: assets/fonts/PoppinsSemiBold.ttf

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf

