name: expense_manager
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  get: ^4.6.6
  video_player: ^2.9.1
  uuid: ^4.4.2
  cloud_firestore: ^5.1.0
  dropdown_button2: ^2.3.9
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsLight.ttf
        - asset: assets/fonts/PoppinsMedium.ttf
        - asset: assets/fonts/PoppinsRegular.ttf
        - asset: assets/fonts/PoppinsSemiBold.ttf
